import { Inter } from "next/font/google";
import "./css/bootstrap.min.css"
import "./css/animate.css"
import "./css/select2.min.css"
import "./css/bootstrap-datepicker.min.css"
import "./css/dataTables.bootstrap5.min.css"
import Header from "../components/header/header";
import Sidebar from "../components/sidebar/sidebar";
import ParentHeader from "@/components/parentHeader";
import "bootstrap/dist/css/bootstrap.min.css";

// import "./css/all.min.css"
// import "./css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, closeChildren }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body className={inter.className}>
        <div className="main-wrapper">
          <ParentHeader />
          <div className={!closeChildren ? "page-wrapper" : "page-wrapper1"} style={{ minHeight: '377px' }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
