import { Inter } from "next/font/google";
import "./css/bootstrap.min.css"
import "./css/animate.css"
import "./css/select2.min.css"
import "./css/bootstrap-datepicker.min.css"
import "./css/dataTables.bootstrap5.min.css"
import Header from "../components/shared/header/header";
import Sidebar from "../components/shared/sidebar/sidebar";
import "bootstrap/dist/css/bootstrap.min.css";
import { Providers } from './redux/provider';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body className={inter.className}>
        <Providers>
          <div className="main-wrapper">
            <Header />
            <Sidebar />
              <div>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
